### ISSUE TITLE
Improve error message when docker is not running

### ISSUE THREAD

**Issue by hectorj2f** [tern-tools/tern#1073]
**Describe the bug**
When docker service is not running yet, you get an error that is not very descriptive of the current issue. Perhaps tern should check if docker is running or installed would be enough.

**To Reproduce**
1. Stop docker service
2. Run tern command

**Error in terminal**
```
tern report -f cyclonedxjson -i debian:jessie -o tern-bom.json
2021-10-27 12:48:45,622 - DEBUG - __main__ - Starting...
2021-10-27 12:48:45,623 - DEBUG - prep - Setting up...
2021-10-27 12:48:45,623 - DEBUG - run - Starting analysis...
Traceback (most recent call last):
  File "/Users/hectorj2f/ternenv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/Users/hectorj2f/ternenv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1279, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1325, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1274, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1034, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 974, in send
    self.connect()
  File "/Users/hectorj2f/ternenv/lib/python3.9/site-packages/docker/transport/unixconn.py", line 30, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by rnjudge** [comment]
Hi @hectorj2f -- if you have a chance, can you [give these](https://github.com/tern-tools/tern/pull/1075) changes a try? They fixed the error for me and I now see Tern exit gracefully when the docker and docker.socket dameons are stopped.

**Comment by hectorj2f** [comment]
thanks @rnjudge! It works for me now.
