### ISSUE TITLE
Generating CycloneDX SBOM fails

### ISSUE THREAD

**Issue by JDemler** [tern-tools/tern#1097]
`./docker_run.sh ternd "report -f cyclonedxjson -i debian:buster" > bom.json` fails with `AttributeError: 'OCIImage' object has no attribute 'repotags'`

**To Reproduce**
1. clone repository
2. build tern using `docker build -f docker/Dockerfile -t ternd .` 
3. run `./docker_run.sh ternd "report -f cyclonedxjson -i debian:buster" > bom.json`

**Error in terminal**
```
2021-12-29 15:03:55,655 - DEBUG - core - Processing Debian copyrights...
2021-12-29 15:03:55,844 - WARNING - core - Some metadata may be missing
2021-12-29 15:04:11,024 - DEBUG - generator - Generating CycloneDX JSON document...
Traceback (most recent call last):
  File "/usr/local/bin/tern", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/tern/__main__.py", line 286, in main
    do_main(args)
  File "/usr/local/lib/python3.9/site-packages/tern/__main__.py", line 116, in do_main
    crun.execute_image(args)
  File "/usr/local/lib/python3.9/site-packages/tern/analyze/default/container/run.py", line 82, in execute_image
    report.report_out(args, full_image)
  File "/usr/local/lib/python3.9/site-packages/tern/report/report.py", line 86, in report_out
    report = generate_report(args, *images)
  File "/usr/local/lib/python3.9/site-packages/tern/report/report.py", line 41, in generate_report
    return generate_format(
  File "/usr/local/lib/python3.9/site-packages/tern/report/report.py", line 56, in generate_format
    return mgr.driver.generate(images, print_inclusive)
  File "/usr/local/lib/python3.9/site-packages/tern/formats/cyclonedx/cyclonedxjson/generator.py", line 60, in generate
    report = get_document_dict(image_obj_list)
  File "/usr/local/lib/python3.9/site-packages/tern/formats/cyclonedx/cyclonedxjson/generator.py", line 41, in get_document_dict
    docu_dict['metadata']['component'] = mhelpers.get_image_dict(image_obj_list[0])
  File "/usr/local/lib/python3.9/site-packages/tern/formats/cyclonedx/cyclonedxjson/image_helpers.py", line 31, in get_image_dict
    if image_obj.repotags:
AttributeError: 'OCIImage' object has no attribute 'repotags'
```

**Expected behavior**
When removing the `-f cyclonedxjson` flag everything works as expected.

**Environment you are running Tern on**
Enter all that apply
```  ./docker_run.sh ternd "--version"
Tern version 2.9.0
   python version = 3.9.9 (main, Dec 21 2021, 10:35:05)
```

On WSL2 Ubuntu:
`Linux --- 5.10.60.1-microsoft-standard-WSL2 #1 SMP Wed Aug 25 23:20:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by rnjudge** [comment]
Thanks for the report @JDemler! Will get going on a fix for this.
