### ISSUE TITLE
Scanning is not possible due to a Python Index Error.

### ISSUE THREAD

**Issue by yamaken1343** [tern-tools/tern#1100]
**Describe the bug**

Scanning is not possible due to a Python Index Error.

**To Reproduce**
1. Run to tern report
2. See error

**Error in terminal**
I use `docker/Dockerfile`

```
$ sudo docker run --rm ternd report -i debian:buster
2022-01-12 10:29:40,320 - DEBUG - __main__ - Starting...
2022-01-12 10:29:40,320 - DEBUG - prep - Setting up...
2022-01-12 10:29:40,321 - DEBUG - rootfs - Running command: chmod +x /usr/local/lib/python3.9/site-packages/tern/tools/fs_hash.sh
2022-01-12 10:29:40,330 - DEBUG - run - Starting analysis...
2022-01-12 10:29:40,331 - DEBUG - skopeo - Attempting to pull image "debian:buster"
2022-01-12 10:29:40,331 - DEBUG - rootfs - Running command: skopeo copy docker://debian:buster dir:/root/.tern/temp
2022-01-12 10:29:47,038 - DEBUG - rootfs - Running command: tar -tf /root/.tern/temp/9b99af5931b39ce167150ad668cfa57ddf7664697be9996cb7e0e6aebbf05843
2022-01-12 10:29:48,636 - DEBUG - rootfs - Running command: tar -x -f /root/.tern/temp/9b99af5931b39ce167150ad668cfa57ddf7664697be9996cb7e0e6aebbf05843 -C /root/.tern/temp/1/contents
2022-01-12 10:29:51,157 - DEBUG - rootfs - Running command: /usr/local/lib/python3.9/site-packages/tern/tools/fs_hash.sh /root/.tern/temp/1/contents
2022-01-12 10:30:08,674 - DEBUG - common - Reading files in filesystem...
Traceback (most recent call last):
  File "/usr/local/bin/tern", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/tern/__main__.py", line 286, in main
    do_main(args)
  File "/usr/local/lib/python3.9/site-packages/tern/__main__.py", line 116, in do_main
    crun.execute_image(args)
  File "/usr/local/lib/python3.9/site-packages/tern/analyze/default/container/run.py", line 80, in execute_image
    cimage.analyze(full_image, args)
  File "/usr/local/lib/python3.9/site-packages/tern/analyze/default/container/image.py", line 81, in analyze
    default_analyze(image_obj, options)
  File "/usr/local/lib/python3.9/site-packages/tern/analyze/default/container/image.py", line 67, in default_analyze
    prereqs = single_layer.analyze_first_layer(image_obj, master_list, options)
  File "/usr/local/lib/python3.9/site-packages/tern/analyze/default/container/single_layer.py", line 148, in analyze_first_layer
    if not com.load_from_cache(image_obj.layers[0], options.redo):
  File "/usr/local/lib/python3.9/site-packages/tern/analyze/common.py", line 77, in load_from_cache
    layer.add_files()
  File "/usr/local/lib/python3.9/site-packages/tern/classes/image_layer.py", line 353, in add_files
    file_data = FileData(os.path.basename(file_info[2]),
IndexError: list index out of range
```

**Expected behavior**
https://github.com/tern-tools/tern/blob/723f43dcaae2f2f0a08a63e5e8de3938031a386e/tern/classes/image_layer.py#L349-L360

It is expected that only the format `permissions|uid|gid|size|hard links|  sha256sum  filepath` will be included in `line`.
But it actually has a different format.
Below is the result of `print(line)`.

```
-rw-r--r--|0|0|498|1|  9d1817f3f797fbf564bf1a17d3de905a8cfc3ecd101d4004c482c263fecf9dc3  ./usr/local/lib/python3.10/site-packages/pip/_vendor/urllib3/util/queue.py

# file: usr/local/lib/python3.10/site-packages/pip/_vendor/urllib3/util/queue.py

security.selinux="system_u:object_r:container_share_t:s0"



-rw-r--r--|0|0|4123|1|  367cda10a4353dabb0e4c14c57a1e68043072137f402e6bd7d0bb38b6b99cc67  ./usr/local/lib/python3.10/site-packages/pip/_vendor/urllib3/util/request.py

# file: usr/local/lib/python3.10/site-packages/pip/_vendor/urllib3/util/request.py

security.selinux="system_u:object_r:container_share_t:s0"

```
The extra output is due to `getfattr`. (<https://github.com/tern-tools/tern/blob/main/tern/tools/fs_hash.sh#L23>)

You need to either remove `getfattr` (I don't know if you can remove it!) or restore the regex compiling that you deleted in 
1551162c3f89a1edcb0c72e6d9a568ad1128d730 .

**Environment you are running Tern on**
Enter all that apply
- Output of 'tern --version'
```
$ sudo docker run --rm ternd -v
Tern version 2.9.0
   python version = 3.9.9 (main, Dec 21 2021, 10:35:05)
```
- Operating System (Linux Distro and version or Mac or Windows)
```
$ cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)
```
- Vagrant file No
- Container OS python:3.9-slim-buster (`docker/Dockerfile`)
- Python version (3.6 or higher) 3.9.9
- Cloud environment (AWS, Azure, GCP) No

**Comment by nishakm** [comment]
OK, I'm able to reproduce on a CentOS Vagrant Box. I get what you're saying now. I will submit a fix shortly.
