### ISSUE TITLE
Error in the CycloneDX JSON report with ci/Dockerfile

### ISSUE THREAD

**Issue by ThiefaineM** [tern-tools/tern#1139]
**Describe the bug**
Asking Tern to generate the report in the cyclonedx json format make it bug. Other format such as json or yaml does not bug.

**To Reproduce**
The Docker is run in Gitlab CI.
1. Build and run the Dockerfile from the ci file
2. Push the Docker to the container and use it in a pipeline
3. Launch Tern on a Dockerfile and put the report format as cyclonedxjson : tern report -f cyclonedxjson -d Dockerfile -o output.json
4. Error when Tern try to generate the CycloneDX report

**Error in terminal**
```
2022-03-28 08:54:55,489 - DEBUG - generator - Generating CycloneDX JSON document...
Traceback (most recent call last):
  File "/usr/local/bin/tern", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/tern/__main__.py", line 309, in main
    do_main(args)
  File "/usr/local/lib/python3.9/site-packages/tern/__main__.py", line 115, in do_main
    drun.execute_dockerfile(args)
  File "/usr/local/lib/python3.9/site-packages/tern/analyze/default/dockerfile/run.py", line 217, in execute_dockerfile
    report.report_out(args, *image_list)
  File "/usr/local/lib/python3.9/site-packages/tern/report/report.py", line 86, in report_out
    report = generate_report(args, *images)
  File "/usr/local/lib/python3.9/site-packages/tern/report/report.py", line 41, in generate_report
    return generate_format(
  File "/usr/local/lib/python3.9/site-packages/tern/report/report.py", line 56, in generate_format
    return mgr.driver.generate(images, print_inclusive)
  File "/usr/local/lib/python3.9/site-packages/tern/formats/cyclonedx/cyclonedxjson/generator.py", line 60, in generate
    report = get_document_dict(image_obj_list)
  File "/usr/local/lib/python3.9/site-packages/tern/formats/cyclonedx/cyclonedxjson/generator.py", line 45, in get_document_dict
    image_componet = mhelpers.get_image_dict(image_obj)
  File "/usr/local/lib/python3.9/site-packages/tern/formats/cyclonedx/cyclonedxjson/image_helpers.py", line 30, in get_image_dict
    purl = PackageURL('docker', None, image_dict['name'], image_dict['version'])
  File "/usr/local/lib/python3.9/site-packages/packageurl/__init__.py", line 238, in __new__
    raise ValueError('Invalid purl: {} is a required argument.'
ValueError: Invalid purl: name is a required argument.
```

**Expected behavior**
As for the others format, it should generate the report. 

**Environment you are running Tern on**
- Docker image in the ci file
- The file dist/tern-*.tar.gz in the Docker file as been change to dist/tern-*.whl because ``` python setup.py bdist_wheel ``` generate a .whl file

**Please attach files if they exist**
- [tern.log](https://github.com/tern-tools/tern/files/8361244/tern.log)

**Comment by zhenik** [comment]
Hi @ThiefaineM , what was the solution? I faced with the same issue
