### ISSUE TITLE
Replace a directory with a symlink seems to confuse the scripts 

### ISSUE THREAD

**Issue by raphaelcoeffic** [tern-tools/tern#1189]
**Describe the bug**

When running `tern` on a docker image that has this statement:
```
RUN \
    echo "\n#\n#\n# creating symlink from old root dir\n#\n#\n" && \
    rm -rf /root && ln -s /data/root /root
```

The following error spilled while `tern` is processing the layer:
```
2022-10-27 15:42:58,341 - DEBUG - rootfs - Running command: cp -r /root/.tern/temp/9/contents/etc /root/.tern/temp/9/contents/tmp /root/.tern/temp/mergedir
2022-10-27 15:43:07,918 - DEBUG - common - Reading files in filesystem...
2022-10-27 15:43:07,919 - DEBUG - rootfs - Running command: cp -r /root/.tern/temp/10/contents/root /root/.tern/temp/mergedir
2022-10-27 15:43:08,186 - ERROR - rootfs - Command failed. cp: cannot overwrite directory '/root/.tern/temp/mergedir/root' with non-directory

Traceback (most recent call last):
  File "/usr/local/bin/tern", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/tern/__main__.py", line 309, in main
    do_main(args)
  File "/usr/local/lib/python3.9/site-packages/tern/__main__.py", line 123, in do_main
    crun.execute_image(args)
  File "/usr/local/lib/python3.9/site-packages/tern/analyze/default/container/run.py", line 80, in execute_image
    cimage.default_analyze(full_image, args)
  File "/usr/local/lib/python3.9/site-packages/tern/analyze/default/container/image.py", line 74, in default_analyze
    multi_layer.analyze_subsequent_layers(
  File "/usr/local/lib/python3.9/site-packages/tern/analyze/default/container/multi_layer.py", line 168, in analyze_subsequent_layers
    fresh_analysis(image_obj, curr_layer, prereqs, options)
  File "/usr/local/lib/python3.9/site-packages/tern/analyze/default/container/multi_layer.py", line 113, in fresh_analysis
    target = prep_layers(image_obj, curr_layer, options.driver)
  File "/usr/local/lib/python3.9/site-packages/tern/analyze/default/container/multi_layer.py", line 71, in prep_layers
    return apply_layers(image_obj, top_layer)
  File "/usr/local/lib/python3.9/site-packages/tern/analyze/default/container/multi_layer.py", line 63, in apply_layers
    rootfs.root_command(['cp', '-r'] + glob.glob(layer_contents), target)
  File "/usr/local/lib/python3.9/site-packages/tern/utils/rootfs.py", line 71, in root_command
    raise subprocess.CalledProcessError(  # nosec
subprocess.CalledProcessError: Command '['cp', '-r', '/root/.tern/temp/10/contents/root', '/root/.tern/temp/mergedir']' returned non-zero exit status 1.
```

**To Reproduce**
1. Make a `Dockerfile` that replaces `/root` directory with a symlink somewhere else
2. Build the container image
3. Push to registry
4. Run `tern` on that container image

**Environment you are running Tern on**

`Tern` is run within a Docker container.

- Output of 'tern --version'
```
Version: 2.10.1
```
- Operating System (Linux Distro and version or Mac or Windows)
```
❯ cat /etc/centos-release
CentOS Linux release 7.9.2009 (Core)

❯ uname -a
Linux docker 3.10.0-1160.76.1.el7.x86_64 #1 SMP Wed Aug 10 16:21:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
- Python version (3.6 or higher): 
```
❯ docker run -it --rm --entrypoint /bin/bash ternd
root@7d03c9e9c32b:/# python --version
Python 3.9.15
```

**Comment by rnjudge** [comment]
Thanks for this issue @raphaelcoeffic -- I'll take a look!

**Comment by rnjudge** [comment]
The issue is with the bulk copying of the layer contents using `cp -r` when dealing with symlinks at the directory level. cp doesn't recognize the unzipped directory symlink, `/root/.tern/temp/3/contents/root` (symlinked to -> `/data/root`) to be a valid directory replacement for copying to the working directory. Looping in @nishakm for ideas. 


Adding the `-L` option to cp and running `cp -rL`, which may properly copy the adds significant overhead to the runtime (20+ minutes before I cancelled it vs 15 seconds for `cp -r`). rsync may be an option?

**Comment by nishakm** [comment]
@rnjudge To clarify, does the error occur when running `cp -r container_layer_dir working_dir` where `container_layer_dir` is a symlink to `random_dir_path`?

**Comment by rnjudge** [comment]
> @rnjudge To clarify, does the error occur when running `cp -r container_layer_dir working_dir` where `container_layer_dir` is a symlink to `random_dir_path`?

@nishakm Yep! In this case, the dockerfile has something like: `ln -s /data/root /root` in it and during analysis Tern tries to `cp -r /root/.tern/temp/3/contents/root /root/.tern/temp/mergedir` but `/root/.tern/temp/3/contents/root` is a symlink and therefore doesn't get recognized as a directory that can be copied to `/root/.tern/temp/mergedir`.
