### ISSUE TITLE
Issue while running the multistage docker scan

### ISSUE THREAD

**Issue by yogeshmpandey** [tern-tools/tern#1207]
**Describe the bug**
I am following this documentation to run the tern scan for multistage builds and running into an issue as below. 

[https://github.com/tern-tools/tern/blob/main/docs/releases/v2_3_0.md#summary](https://github.com/tern-tools/tern/blob/main/docs/releases/v2_3_0.md#summary )

**To Reproduce**
1. clone the repo
2. run the command 
` docker build -f docker/Dockerfile.scancode . -t ternscantesst`
4. upload the build image to docker hub
5. run the script 
`docker_run.sh ternscantest "report -x scancode -i yogeshpandey/ternscantesst:latest"
`

**Error in terminal**
```
./docker_run.sh ternscantest "report -x scancode -i yogeshpandey/ternscantesst:latest"
2023-01-05 07:15:53,611 - DEBUG - __main__ - Starting...
2023-01-05 07:15:53,611 - DEBUG - prep - Setting up...
2023-01-05 07:15:53,611 - DEBUG - rootfs - Running command: chmod +x /usr/local/lib/python3.9/site-packages/tern/tools/fs_hash.sh
2023-01-05 07:15:53,671 - DEBUG - run - Starting analysis...
2023-01-05 07:15:53,671 - DEBUG - skopeo - Attempting to pull image "yogeshpandey/ternscantesst:latest"
2023-01-05 07:15:53,672 - DEBUG - rootfs - Running command: skopeo copy docker://yogeshpandey/ternscantesst:latest dir:/root/.tern/temp
2023-01-05 07:16:13,444 - DEBUG - skopeo - Inspecting remote image "yogeshpandey/ternscantesst:latest"
2023-01-05 07:16:13,445 - DEBUG - rootfs - Running command: skopeo inspect docker://yogeshpandey/ternscantesst:latest
2023-01-05 07:16:19,276 - DEBUG - rootfs - Running command: tar -tf /root/.tern/temp/b52ebda398ed2c4602ea06056f78d45a59474ee4e2a020967251ba082424e7e2
2023-01-05 07:16:19,810 - DEBUG - rootfs - Running command: tar -x -f /root/.tern/temp/b52ebda398ed2c4602ea06056f78d45a59474ee4e2a020967251ba082424e7e2 -C /root/.tern/temp/1/contents
2023-01-05 07:16:20,410 - DEBUG - rootfs - Running command: /usr/local/lib/python3.9/site-packages/tern/tools/fs_hash.sh /root/.tern/temp/1/contents
2023-01-05 07:16:25,064 - DEBUG - rootfs - Running command: tar -tf /root/.tern/temp/5ea3b77facf9f24e5cda370be6af00cfc85988f3140bee862e2529dd50e6eec1
2023-01-05 07:16:25,122 - DEBUG - rootfs - Running command: tar -x -f /root/.tern/temp/5ea3b77facf9f24e5cda370be6af00cfc85988f3140bee862e2529dd50e6eec1 -C /root/.tern/temp/2/contents
2023-01-05 07:16:25,191 - DEBUG - rootfs - Running command: /usr/local/lib/python3.9/site-packages/tern/tools/fs_hash.sh /root/.tern/temp/2/contents
2023-01-05 07:16:25,510 - DEBUG - rootfs - Running command: tar -tf /root/.tern/temp/6014e9bf55ec70140b642f61b22517fd155bdc03320eaaa24c4a3da2f47718d3
2023-01-05 07:16:25,712 - DEBUG - rootfs - Running command: tar -x -f /root/.tern/temp/6014e9bf55ec70140b642f61b22517fd155bdc03320eaaa24c4a3da2f47718d3 -C /root/.tern/temp/3/contents
2023-01-05 07:16:25,913 - DEBUG - rootfs - Running command: /usr/local/lib/python3.9/site-packages/tern/tools/fs_hash.sh /root/.tern/temp/3/contents
2023-01-05 07:16:28,231 - DEBUG - rootfs - Running command: tar -tf /root/.tern/temp/2e2ce69d537b55f4b27cef25bc78c49454ebd271ba89a8a118bdb463248fc586
2023-01-05 07:16:28,236 - DEBUG - rootfs - Running command: tar -x -f /root/.tern/temp/2e2ce69d537b55f4b27cef25bc78c49454ebd271ba89a8a118bdb463248fc586 -C /root/.tern/temp/4/contents
2023-01-05 07:16:28,239 - DEBUG - rootfs - Running command: /usr/local/lib/python3.9/site-packages/tern/tools/fs_hash.sh /root/.tern/temp/4/contents
2023-01-05 07:16:28,243 - DEBUG - rootfs - Running command: tar -tf /root/.tern/temp/b66cb6540a3a7328e9cca5d2b76e50eaada22881c826119d47134e44933b0362
2023-01-05 07:16:28,314 - DEBUG - rootfs - Running command: tar -x -f /root/.tern/temp/b66cb6540a3a7328e9cca5d2b76e50eaada22881c826119d47134e44933b0362 -C /root/.tern/temp/5/contents
2023-01-05 07:16:28,481 - DEBUG - rootfs - Running command: /usr/local/lib/python3.9/site-packages/tern/tools/fs_hash.sh /root/.tern/temp/5/contents
2023-01-05 07:16:30,132 - DEBUG - rootfs - Running command: tar -tf /root/.tern/temp/b1f9735ac802f5eb5f969b5a9a02e40c7efe53ecb808e0dce04fe36105c6523e
2023-01-05 07:16:30,873 - DEBUG - rootfs - Running command: tar -x -f /root/.tern/temp/b1f9735ac802f5eb5f969b5a9a02e40c7efe53ecb808e0dce04fe36105c6523e -C /root/.tern/temp/6/contents
2023-01-05 07:16:31,644 - DEBUG - rootfs - Running command: /usr/local/lib/python3.9/site-packages/tern/tools/fs_hash.sh /root/.tern/temp/6/contents
2023-01-05 07:16:35,769 - DEBUG - rootfs - Running command: tar -tf /root/.tern/temp/209d592e5d89ffc15c0143e842122e9e8410d4f2e41b3da850c9b113fa6062ca
2023-01-05 07:16:38,691 - DEBUG - rootfs - Running command: tar -x -f /root/.tern/temp/209d592e5d89ffc15c0143e842122e9e8410d4f2e41b3da850c9b113fa6062ca -C /root/.tern/temp/7/contents
2023-01-05 07:16:44,684 - DEBUG - rootfs - Running command: /usr/local/lib/python3.9/site-packages/tern/tools/fs_hash.sh /root/.tern/temp/7/contents
2023-01-05 07:20:28,234 - DEBUG - common - Reading files in filesystem...
2023-01-05 07:20:29,461 - DEBUG - rootfs - Running command: tar -tf /root/.tern/temp/b52ebda398ed2c4602ea06056f78d45a59474ee4e2a020967251ba082424e7e2
2023-01-05 07:20:29,960 - DEBUG - rootfs - Running command: tar -x -f /root/.tern/temp/b52ebda398ed2c4602ea06056f78d45a59474ee4e2a020967251ba082424e7e2 -C /root/.tern/temp/mergedir
2023-01-05 07:20:30,747 - DEBUG - rootfs - Running command: mknod /root/.tern/temp/mergedir/dev/urandom c 1 9
2023-01-05 07:20:30,772 - DEBUG - rootfs - Running command: cp /etc/resolv.conf /root/.tern/temp/mergedir/etc/resolv.conf
2023-01-05 07:20:30,775 - DEBUG - core - Collecting metadata for image layer...
2023-01-05 07:20:30,776 - DEBUG - rootfs - Running command: chroot /root/.tern/temp/mergedir /bin/sh -c dpkg-query -W -f '${Package}
'
2023-01-05 07:20:30,782 - DEBUG - rootfs - Running command: chroot /root/.tern/temp/mergedir /bin/sh -c pkgs=`dpkg-query -W -f '${Package}
'` && for p in $pkgs; do files=`dpkg-query -L $p`; for file in $files; do if [ -f $file ]; then echo $file; fi; done; echo LICF; done
2023-01-05 07:20:31,119 - DEBUG - rootfs - Running command: chroot /root/.tern/temp/mergedir /bin/sh -c dpkg-query -W -f '${Version}
'
2023-01-05 07:20:31,127 - DEBUG - rootfs - Running command: chroot /root/.tern/temp/mergedir /bin/sh -c pkgs=`dpkg-query -W -f '${Package}
'` && for p in $pkgs; do dpkg-query -f '${source:Package}
' -W $p; done
2023-01-05 07:20:31,411 - DEBUG - rootfs - Running command: chroot /root/.tern/temp/mergedir /bin/sh -c pkgs=`dpkg-query -W -f '${Package}
'` && for p in $pkgs; do /bin/cat /usr/share/doc/$p/copyright; echo LICF; done
2023-01-05 07:20:31,486 - DEBUG - rootfs - Running command: chroot /root/.tern/temp/mergedir /bin/sh -c dpkg-query -W -f '${Homepage}
' | /bin/sed 's/^$/Unknown/'
2023-01-05 07:20:31,495 - DEBUG - rootfs - Running command: chroot /root/.tern/temp/mergedir /bin/sh -c pkgs=`dpkg-query -W -f '${Package}
'` && for p in $pkgs; do dpkg-query -f '${source:Version}
' -W $p; done
2023-01-05 07:20:31,738 - DEBUG - core - Processing Debian copyrights...
2023-01-05 07:20:31,914 - WARNING - core - Some metadata may be missing
2023-01-05 07:20:38,213 - DEBUG - rootfs - Running command: /usr/local/bin/scancode -ilpcu --quiet --timeout 300 -n 7 --json - /root/.tern/temp/1/contents
Traceback (most recent call last):
  File "/usr/local/bin/tern", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/tern/__main__.py", line 311, in main
    do_main(args)
  File "/usr/local/lib/python3.9/site-packages/tern/__main__.py", line 123, in do_main
    crun.execute_image(args)
  File "/usr/local/lib/python3.9/site-packages/tern/analyze/default/container/run.py", line 80, in execute_image
    cimage.default_analyze(full_image, args)
  File "/usr/local/lib/python3.9/site-packages/tern/analyze/default/container/image.py", line 70, in default_analyze
    passthrough.run_extension_layer(image_obj.layers[0], options.extend,
  File "/usr/local/lib/python3.9/site-packages/tern/analyze/passthrough.py", line 92, in run_extension_layer
    return mgr.driver.execute_layer(image_layer, redo)
  File "/usr/local/lib/python3.9/site-packages/tern/extensions/scancode/executor.py", line 219, in execute_layer
    file_list, package_list = collect_layer_data(image_layer)
  File "/usr/local/lib/python3.9/site-packages/tern/extensions/scancode/executor.py", line 162, in collect_layer_data
    files.append(get_scancode_file(f))
  File "/usr/local/lib/python3.9/site-packages/tern/extensions/scancode/executor.py", line 65, in get_scancode_file
    fd.copyrights = [c['value'] for c in file_dict['copyrights']]
  File "/usr/local/lib/python3.9/site-packages/tern/extensions/scancode/executor.py", line 65, in <listcomp>
    fd.copyrights = [c['value'] for c in file_dict['copyrights']]
KeyError: 'value'
```

**Expected behaviour**
The tool should be able to generate the scanned report for the multistage docker file. 

**Environment you are running Tern on**
Enter all that apply
- Output of 'tern --version'
N/A, running the script only. 
- Operating System (Linux Distro and version or Mac or Windows)
Ubuntu 20.04
- Vagrant file
- Container OS
As per the example in the link : [https://github.com/tern-tools/tern/blob/main/docs/releases/v2_3_0.md#summary](https://github.com/tern-tools/tern/blob/main/docs/releases/v2_3_0.md#summary)
- Python version (3.6 or higher)
- Cloud environment (AWS, Azure, GCP)

**Please attach files if they exist**
- tern.log
- report.*

**Comment by rnjudge** [comment]
Hi @yogeshmpandey thanks for this bug. I think this is actually an error with Scancode unrelated to the multistage of the Dockerfile. The same bug was opened here: https://github.com/tern-tools/tern/issues/1202. I will close this bug as a duplicate and track the fix in 1202.

Additionally, you will note in the release notes you reference that Tern only works on multistage _Dockerfiles_, not docker images built with Dockerfiles, so running Tern on a multistage image you pushed to a registry is not the intended usage here. With that said, I will work on a fix for the scancode issue!
