### ISSUE TITLE
Fails when scanning node:latest

### ISSUE THREAD

**Issue by tevoinea** [tern-tools/tern#634]
**Describe the bug**
I created my own Dockerfile to run tern in a Windows environment. I know it's not officially supported but I'm hoping you can help point me in the right direction.

I started with a Ubuntu:18.04 container, installed python 3.8, pip to use the latest python and then tern.

The command to run the container `docker run --privileged -v //var/run/docker.sock:/var/run/docker.sock --mount type=bind,source=D:\tern\workdir,target=/hostmount --rm ternd report -f json -i node:latest > node_latest.json`

**Error in terminal**
```
2020-04-13 22:23:08,294 - DEBUG - __main__ - Starting...
2020-04-13 22:23:08,295 - DEBUG - run - Setting up...
2020-04-13 22:23:08,300 - DEBUG - container - Checking if image "node:latest" is available on disk...
2020-04-13 22:23:08,304 - DEBUG - container - Image "node:latest" found
2020-04-13 22:23:18,612 - DEBUG - rootfs - Running command: tar -tf /root/.tern/temp.tar
2020-04-13 22:23:18,617 - DEBUG - rootfs - Running command: tar -xf /root/.tern/temp.tar -C /root/.tern/temp
2020-04-13 22:23:19,695 - DEBUG - rootfs - Running command: tar -tf /root/.tern/temp/74f173c080ceff9b6edc84583580302ac70fa623228622c1ea5fca1b527d4f62/layer.tar
2020-04-13 22:23:19,717 - DEBUG - rootfs - Running command: tar -xf /root/.tern/temp/74f173c080ceff9b6edc84583580302ac70fa623228622c1ea5fca1b527d4f62/layer.tar -C /root/.tern/temp/74f173c080ceff9b6edc84583580302ac70fa623228622c1ea5fca1b527d4f62/contents
2020-04-13 22:23:20,055 - DEBUG - rootfs - Running command: /usr/local/lib/python3.8/dist-packages/tern/tools/fs_hash.sh /root/.tern/temp/74f173c080ceff9b6edc84583580302ac70fa623228622c1ea5fca1b527d4f62/contents
2020-04-13 22:23:29,270 - DEBUG - rootfs - Running command: tar -tf /root/.tern/temp/6174f10d72918fa2fefee4c1d939ef0c874f423568f0e088fab0a17b2531221b/layer.tar
2020-04-13 22:23:29,288 - DEBUG - rootfs - Running command: tar -xf /root/.tern/temp/6174f10d72918fa2fefee4c1d939ef0c874f423568f0e088fab0a17b2531221b/layer.tar -C /root/.tern/temp/6174f10d72918fa2fefee4c1d939ef0c874f423568f0e088fab0a17b2531221b/contents
2020-04-13 22:23:29,348 - DEBUG - rootfs - Running command: /usr/local/lib/python3.8/dist-packages/tern/tools/fs_hash.sh /root/.tern/temp/6174f10d72918fa2fefee4c1d939ef0c874f423568f0e088fab0a17b2531221b/contents
2020-04-13 22:23:30,713 - DEBUG - rootfs - Running command: tar -tf /root/.tern/temp/85456e98ddec9427741fdacc1e0ec32fb2aa470b3951edf2c150452517765415/layer.tar
2020-04-13 22:23:30,718 - DEBUG - rootfs - Running command: tar -xf /root/.tern/temp/85456e98ddec9427741fdacc1e0ec32fb2aa470b3951edf2c150452517765415/layer.tar -C /root/.tern/temp/85456e98ddec9427741fdacc1e0ec32fb2aa470b3951edf2c150452517765415/contents
2020-04-13 22:23:30,735 - DEBUG - rootfs - Running command: /usr/local/lib/python3.8/dist-packages/tern/tools/fs_hash.sh /root/.tern/temp/85456e98ddec9427741fdacc1e0ec32fb2aa470b3951edf2c150452517765415/contents
2020-04-13 22:23:31,121 - DEBUG - rootfs - Running command: tar -tf /root/.tern/temp/197a5bbc448b41162da545750915dfc72852ef205c5ce6543068f018835c30bc/layer.tar
2020-04-13 22:23:31,147 - DEBUG - rootfs - Running command: tar -xf /root/.tern/temp/197a5bbc448b41162da545750915dfc72852ef205c5ce6543068f018835c30bc/layer.tar -C /root/.tern/temp/197a5bbc448b41162da545750915dfc72852ef205c5ce6543068f018835c30bc/contents
2020-04-13 22:23:31,479 - DEBUG - rootfs - Running command: /usr/local/lib/python3.8/dist-packages/tern/tools/fs_hash.sh /root/.tern/temp/197a5bbc448b41162da545750915dfc72852ef205c5ce6543068f018835c30bc/contents
2020-04-13 22:23:41,758 - DEBUG - rootfs - Running command: tar -tf /root/.tern/temp/3797effdb00b7924ca9fb81947f45d4f45dcd98feb72a54f7625f2e63d5ad454/layer.tar
2020-04-13 22:23:41,825 - DEBUG - rootfs - Running command: tar -xf /root/.tern/temp/3797effdb00b7924ca9fb81947f45d4f45dcd98feb72a54f7625f2e63d5ad454/layer.tar -C /root/.tern/temp/3797effdb00b7924ca9fb81947f45d4f45dcd98feb72a54f7625f2e63d5ad454/contents
2020-04-13 22:23:42,924 - DEBUG - rootfs - Running command: /usr/local/lib/python3.8/dist-packages/tern/tools/fs_hash.sh /root/.tern/temp/3797effdb00b7924ca9fb81947f45d4f45dcd98feb72a54f7625f2e63d5ad454/contents
2020-04-13 22:24:08,956 - DEBUG - rootfs - Running command: tar -tf /root/.tern/temp/a0016126b0661a06111a55b0530f833d95875027c764909d25bebfdfc6c71c14/layer.tar
2020-04-13 22:24:08,961 - DEBUG - rootfs - Running command: tar -xf /root/.tern/temp/a0016126b0661a06111a55b0530f833d95875027c764909d25bebfdfc6c71c14/layer.tar -C /root/.tern/temp/a0016126b0661a06111a55b0530f833d95875027c764909d25bebfdfc6c71c14/contents
2020-04-13 22:24:08,966 - DEBUG - rootfs - Running command: /usr/local/lib/python3.8/dist-packages/tern/tools/fs_hash.sh /root/.tern/temp/a0016126b0661a06111a55b0530f833d95875027c764909d25bebfdfc6c71c14/contents
2020-04-13 22:24:09,009 - DEBUG - rootfs - Running command: tar -tf /root/.tern/temp/e8c6a0c8ff63bba5ec84e30fc5d758f37118bffd131d10e255b2251123567eae/layer.tar
2020-04-13 22:24:09,031 - DEBUG - rootfs - Running command: tar -xf /root/.tern/temp/e8c6a0c8ff63bba5ec84e30fc5d758f37118bffd131d10e255b2251123567eae/layer.tar -C /root/.tern/temp/e8c6a0c8ff63bba5ec84e30fc5d758f37118bffd131d10e255b2251123567eae/contents
2020-04-13 22:24:09,262 - DEBUG - rootfs - Running command: /usr/local/lib/python3.8/dist-packages/tern/tools/fs_hash.sh /root/.tern/temp/e8c6a0c8ff63bba5ec84e30fc5d758f37118bffd131d10e255b2251123567eae/contents
2020-04-13 22:24:16,931 - DEBUG - rootfs - Running command: tar -tf /root/.tern/temp/3ea2c93b8632d97b1a8c84dafba19a346d702c249af7cd4c1f22fdae229fe207/layer.tar
2020-04-13 22:24:16,935 - DEBUG - rootfs - Running command: tar -xf /root/.tern/temp/3ea2c93b8632d97b1a8c84dafba19a346d702c249af7cd4c1f22fdae229fe207/layer.tar -C /root/.tern/temp/3ea2c93b8632d97b1a8c84dafba19a346d702c249af7cd4c1f22fdae229fe207/contents
2020-04-13 22:24:16,957 - DEBUG - rootfs - Running command: /usr/local/lib/python3.8/dist-packages/tern/tools/fs_hash.sh /root/.tern/temp/3ea2c93b8632d97b1a8c84dafba19a346d702c249af7cd4c1f22fdae229fe207/contents
2020-04-13 22:24:17,043 - DEBUG - rootfs - Running command: tar -tf /root/.tern/temp/8a6f8c432a3d69e137170bb87af8ff5b845868024f89b91fb1fbf1755bef49a3/layer.tar
2020-04-13 22:24:17,047 - DEBUG - rootfs - Running command: tar -xf /root/.tern/temp/8a6f8c432a3d69e137170bb87af8ff5b845868024f89b91fb1fbf1755bef49a3/layer.tar -C /root/.tern/temp/8a6f8c432a3d69e137170bb87af8ff5b845868024f89b91fb1fbf1755bef49a3/contents
2020-04-13 22:24:17,055 - DEBUG - rootfs - Running command: /usr/local/lib/python3.8/dist-packages/tern/tools/fs_hash.sh /root/.tern/temp/8a6f8c432a3d69e137170bb87af8ff5b845868024f89b91fb1fbf1755bef49a3/contents
2020-04-13 22:24:17,064 - DEBUG - common - Reading files in filesystem...
2020-04-13 22:24:19,385 - DEBUG - rootfs - Running command: mount -o bind /root/.tern/temp/74f173c080ceff9b6edc84583580302ac70fa623228622c1ea5fca1b527d4f62/contents /root/.tern/temp/mergedir
2020-04-13 22:24:19,389 - DEBUG - rootfs - Running command: mount -t proc /proc /root/.tern/temp/mergedir/proc
2020-04-13 22:24:19,392 - DEBUG - rootfs - Running command: mount -o bind /sys /root/.tern/temp/mergedir/sys
2020-04-13 22:24:19,397 - DEBUG - rootfs - Running command: mount -o bind /dev /root/.tern/temp/mergedir/dev
2020-04-13 22:24:19,401 - DEBUG - rootfs - Running command: cp /etc/resolv.conf /root/.tern/temp/mergedir/etc/resolv.conf
2020-04-13 22:24:19,409 - DEBUG - rootfs - Running command: unshare -pf --mount-proc=/root/.tern/temp/mergedir/proc chroot /root/.tern/temp/mergedir /bin/bash -c pkgs=`dpkg --get-selections | cut -f1 -d':' | awk '{print $1}'` && for p in $pkgs; do cat /usr/share/doc/$p/copyright; echo LICF; done
2020-04-13 22:24:19,528 - DEBUG - rootfs - Running command: unshare -pf --mount-proc=/root/.tern/temp/mergedir/proc chroot /root/.tern/temp/mergedir /bin/bash -c pkgs=`dpkg --get-selections | cut -f1 -d':' | awk '{print $1}'` && for p in $pkgs; do dpkg -l $p | awk 'NR>5 {print $3}'; done
2020-04-13 22:24:19,881 - DEBUG - rootfs - Running command: unshare -pf --mount-proc=/root/.tern/temp/mergedir/proc chroot /root/.tern/temp/mergedir /bin/bash -c dpkg --get-selections | cut -f1 -d':' | awk '{print $1}'
2020-04-13 22:24:19,907 - WARNING - common - Inconsistent lengths for key: proj_urls
2020-04-13 22:24:19,914 - DEBUG - rootfs - Running command: umount /root/.tern/temp/mergedir/proc
2020-04-13 22:24:19,926 - DEBUG - rootfs - Running command: umount /root/.tern/temp/mergedir/sys
2020-04-13 22:24:19,938 - DEBUG - rootfs - Running command: umount /root/.tern/temp/mergedir/dev
2020-04-13 22:24:19,953 - DEBUG - rootfs - Running command: umount -rl /root/.tern/temp/mergedir
2020-04-13 22:24:19,965 - DEBUG - common - Reading files in filesystem...
2020-04-13 22:24:20,035 - WARNING - command_lib - No listing for key rm. Consider adding this listing to command_lib/snippets.yml.

2020-04-13 22:24:20,035 - DEBUG - rootfs - Running command: mount -t overlay overlay -o lowerdir=/root/.tern/temp/74f173c080ceff9b6edc84583580302ac70fa623228622c1ea5fca1b527d4f62/contents,upperdir=/root/.tern/temp/6174f10d72918fa2fefee4c1d939ef0c874f423568f0e088fab0a17b2531221b/contents,workdir=/root/.tern/temp/workdir /root/.tern/temp/mergedir
2020-04-13 22:24:20,049 - ERROR - rootfs - Command failed. mount: /root/.tern/temp/mergedir: wrong fs type, bad option, bad superblock on overlay, missing codepage or helper program, or other error.

Traceback (most recent call last):
  File "/usr/local/bin/tern", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/tern/__main__.py", line 201, in main
    do_main(args)
  File "/usr/local/lib/python3.8/dist-packages/tern/__main__.py", line 105, in do_main
    run.execute_docker_image(args)
  File "/usr/local/lib/python3.8/dist-packages/tern/analyze/docker/run.py", line 90, in execute_docker_image
    analyze(full_image, args)
  File "/usr/local/lib/python3.8/dist-packages/tern/analyze/docker/run.py", line 69, in analyze
    analyze_docker_image(image_obj, args.redo, dfile_lock, dfobj)
  File "/usr/local/lib/python3.8/dist-packages/tern/analyze/docker/analyze.py", line 42, in analyze_docker_image
    analyze_subsequent_layers(image_obj, shell, master_list, redo, dfobj,
  File "/usr/local/lib/python3.8/dist-packages/tern/analyze/docker/analyze.py", line 133, in analyze_subsequent_layers
    target = mount_overlay_fs(image_obj, curr_layer)
  File "/usr/local/lib/python3.8/dist-packages/tern/analyze/docker/analyze.py", line 191, in mount_overlay_fs
    target = rootfs.mount_diff_layers(tar_layers)
  File "/usr/local/lib/python3.8/dist-packages/tern/utils/rootfs.py", line 221, in mount_diff_layers
    root_command(union_mount, args, merge_dir_path)
  File "/usr/local/lib/python3.8/dist-packages/tern/utils/rootfs.py", line 76, in root_command
    raise subprocess.CalledProcessError(  # nosec
subprocess.CalledProcessError: Command '['mount', '-t', 'overlay', 'overlay', '-o', 'lowerdir=/root/.tern/temp/74f173c080ceff9b6edc84583580302ac70fa623228622c1ea5fca1b527d4f62/contents,upperdir=/root/.tern/temp/6174f10d72918fa2fefee4c1d939ef0c874f423568f0e088fab0a17b2531221b/contents,workdir=/root/.tern/temp/workdir', '/root/.tern/temp/mergedir']' returned non-zero exit status 1.
```

**Expected behavior**
It outputs the report to node_latest.json

**Environment you are running Tern on**
Enter all that apply
- Output of 'tern --version' ```Tern version 2.0.0
   python version = 3.8.0 (default, Oct 28 2019, 16:14:01)```
- Operating System Windows
- Container OS Ubuntu:18.04
- Python version (3.6 or higher) 3.8

**Please attach files if they exist**
- tern.log
- report.*

**Comment by tevoinea** [comment]
It looks like this might have been fixed in #498, has it been published to pip yet?

**Comment by rnjudge** [comment]
Yes, it has been published to the pip package. The issue is likely with your Dockerfile missing an `ENTRYPOINT` command with the `-b` option similar to the default Dockerfile. You need to use the `-b BIND_DIR` option since you cannot overlay mount inside a container and the mount point needs to be somewhere outside the container. A similar issue was reported here and resolved with the correct bind mount option: https://github.com/tern-tools/tern/issues/566

Hope this helps!

**Comment by tevoinea** [comment]
Yup! That was it. Thanks so much! 😀

**Comment by tevoinea** [comment]
@rnjudge Quick follow up now that I'm starting to understand this better.

The reason why tern + docker doesn't work on Windows is because the tools tern uses to expand and overlay the layers are linux specific and there's an incompatibility between the tools and having the mount volume coming from windows.

But, if there's only 1 layer, tern doesn't need to do the overlay so single layer images work.

From that I have 2 questions:

1. Have you considered [squashing](https://docs.docker.com/engine/reference/commandline/image_build/#options) an image before scanning it? Here is the error I got by squashing an image then scanning it using tern in docker:
```
/* snip */
2020-04-14 20:17:02,098 - DEBUG - common - Reading files in filesystem...
Traceback (most recent call last):
  File "/usr/local/bin/tern", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/tern/__main__.py", line 201, in main
    do_main(args)
  File "/usr/local/lib/python3.8/dist-packages/tern/__main__.py", line 105, in do_main
    run.execute_docker_image(args)
  File "/usr/local/lib/python3.8/dist-packages/tern/analyze/docker/run.py", line 90, in execute_docker_image
    analyze(full_image, args)
  File "/usr/local/lib/python3.8/dist-packages/tern/analyze/docker/run.py", line 69, in analyze
    analyze_docker_image(image_obj, args.redo, dfile_lock, dfobj)
  File "/usr/local/lib/python3.8/dist-packages/tern/analyze/docker/analyze.py", line 42, in analyze_docker_image
    analyze_subsequent_layers(image_obj, shell, master_list, redo, dfobj,
  File "/usr/local/lib/python3.8/dist-packages/tern/analyze/docker/analyze.py", line 129, in analyze_subsequent_layers
    command_list = dhelper.get_commands_from_history(
  File "/usr/local/lib/python3.8/dist-packages/tern/analyze/docker/helpers.py", line 158, in get_commands_from_history
    command_line = instruction.split(' ', 1)[1]
UnboundLocalError: local variable 'instruction' referenced before assignment
```

2. I see from a previous issue of mine #625 that running tern without privileges is [on your roadmap](https://github.com/tern-tools/tern/issues/625#issuecomment-610096242), will that enable tern in docker on windows? Is there somewhere I can track that roadmap?

Finally, is there anything I can do to help (with some guidance) to enable tern in docker on windows?

**Comment by nishakm** [comment]
> The reason why tern + docker doesn't work on Windows is because the tools tern uses to expand and overlay the layers are linux specific and there's an incompatibility between the tools and having the mount volume coming from windows.

Exactly! This is why our only option to make tern work on Windows and Mac was to run it on a Vagrant machine. It uses the overlayfs driver which doesn't natively exist on Mac nor Windows.

> 
> But, if there's only 1 layer, tern doesn't need to do the overlay so single layer images work.
> 
> From that I have 2 questions:
> 
> 1. Have you considered [squashing](https://docs.docker.com/engine/reference/commandline/image_build/#options) an image before scanning it? Here is the error I got by squashing an image then scanning it using tern in docker:
> 
> ```
> /* snip */
> 2020-04-14 20:17:02,098 - DEBUG - common - Reading files in filesystem...
> Traceback (most recent call last):
>   File "/usr/local/bin/tern", line 8, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.8/dist-packages/tern/__main__.py", line 201, in main
>     do_main(args)
>   File "/usr/local/lib/python3.8/dist-packages/tern/__main__.py", line 105, in do_main
>     run.execute_docker_image(args)
>   File "/usr/local/lib/python3.8/dist-packages/tern/analyze/docker/run.py", line 90, in execute_docker_image
>     analyze(full_image, args)
>   File "/usr/local/lib/python3.8/dist-packages/tern/analyze/docker/run.py", line 69, in analyze
>     analyze_docker_image(image_obj, args.redo, dfile_lock, dfobj)
>   File "/usr/local/lib/python3.8/dist-packages/tern/analyze/docker/analyze.py", line 42, in analyze_docker_image
>     analyze_subsequent_layers(image_obj, shell, master_list, redo, dfobj,
>   File "/usr/local/lib/python3.8/dist-packages/tern/analyze/docker/analyze.py", line 129, in analyze_subsequent_layers
>     command_list = dhelper.get_commands_from_history(
>   File "/usr/local/lib/python3.8/dist-packages/tern/analyze/docker/helpers.py", line 158, in get_commands_from_history
>     command_line = instruction.split(' ', 1)[1]
> UnboundLocalError: local variable 'instruction' referenced before assignment
> ```

Oh good, a scenario where a docker image has no 'created_by' key. But yes, at this point, there is no need to be looking for what happened in the history because we just look for known binaries in the filesystem. I'd say this is a bug.

> 
> 1. I see from a previous issue of mine #625 that running tern without privileges is [on your roadmap](https://github.com/tern-tools/tern/issues/625#issuecomment-610096242), will that enable tern in docker on windows? Is there somewhere I can track that roadmap?

I'll be doing some backlog scrubbing and updating the roadmap soon. Running tern in a docker container has some problems but we're definitely trying to get rid of the dependency on overlayfs.

> Finally, is there anything I can do to help (with some guidance) to enable tern in docker on windows?

@pombredanne is working on bringing in changes that will help with this issue (specifically replacing overlayfs with just merging in directories which will work within a docker container). Stay tuned!

**Comment by rnjudge** [comment]
> @rnjudge Quick follow up now that I'm starting to understand this better.
> 
> The reason why tern + docker doesn't work on Windows is because the tools tern uses to expand and overlay the layers are linux specific and there's an incompatibility between the tools and having the mount volume coming from windows.
> 
> But, if there's only 1 layer, tern doesn't need to do the overlay so single layer images work.
> 
> From that I have 2 questions:
> 
>     1. Have you considered [squashing](https://docs.docker.com/engine/reference/commandline/image_build/#options) an image before scanning it? 

IMO, squashing the image to avoid overlay mounting is trading one issue for another. If you squash an image, you are re-writing the history of the image, which defeats the purpose of Tern to report what it finds layer by layer in a given image. We cannot rely on what Tern finds after the squash to be the same as what it would find in an un-squashed image. For example, files/packages that are deleted in later layers are purged from the resulting image when it is squashed. This means Tern would not report on the presence or metadata of these files/packages because they would be missing from the squashed image while in the original non-squashed version of the container (that users might be shipping), a footprint of that file would be available.

This is because after squashing you cannot expect that the docker history will reflect the state before squashing. This is also why the created_by field is empty -- squashing cannot populate the history with  meaningful comments.

**Comment by tevoinea** [comment]
> Oh good, a scenario where a docker image has no 'created_by' key. But yes, at this point, there is no need to be looking for what happened in the history because we just look for known binaries in the filesystem. I'd say this is a bug.

Should I create an issue for it?

> @pombredanne is working on bringing in changes that will help with this issue (specifically replacing overlayfs with just merging in directories which will work within a docker container). Stay tuned!

Once the dependency of overlayfs is gone, that should also unblock Windows right?

> This means Tern would not report on the presence or metadata of these files/packages because they would be missing from the squashed image while in the original non-squashed version of the container (that users might be shipping), a footprint of that file would be available.

That's true that users are likely not shipping squashed images right now, especially since it's an experimental feature. 

What do you think of supporting squashed images (not requiring them) as a temporary workaround until the overlayfs dependency is removed? Would it be a big feature? It could be explicitly marked as experimental, nothing would change for unsquashed images and it could unblock the Windows scenario.

**Comment by rnjudge** [comment]
> > Oh good, a scenario where a docker image has no 'created_by' key. But yes, at this point, there is no need to be looking for what happened in the history because we just look for known binaries in the filesystem. I'd say this is a bug.
> 
> Should I create an issue for it?

That would be great!
> 
> > @pombredanne is working on bringing in changes that will help with this issue (specifically replacing overlayfs with just merging in directories which will work within a docker container). Stay tuned!
> 
> Once the dependency of overlayfs is gone, that should also unblock Windows right?

It will be a step in the right direction. As you noted before, there are some linux filesystem utilities we rely on like `getfattr` that are not available on Windows that would need to be tweaked first.

> > This means Tern would not report on the presence or metadata of these files/packages because they would be missing from the squashed image while in the original non-squashed version of the container (that users might be shipping), a footprint of that file would be available.
> 
> That's true that users are likely not shipping squashed images right now, especially since it's an experimental feature.
> 
> What do you think of supporting squashed images (not requiring them) as a temporary workaround until the overlayfs dependency is removed? Would it be a big feature? It could be explicitly marked as experimental, nothing would change for unsquashed images and it could unblock the Windows scenario.

We have other higher-priority items on our roadmap right now that we need to focus on first. Additionally, enabling squashed images and reporting on them does not give the fully transparent summary of what is in the actual un-squashed container image (see example from my previous comment about removing files/packages). This goes against the purpose of Tern which is to give users the most transparent view possible of what's in their container image.  Windows users are not blocked from using Tern, as vagrant is a viable and tested workaround. Therefore, I would suggest using that until the overlayfs dependency is removed.

**Comment by nishakm** [comment]
@tevoinea Alternatively, if you really need this on Windows, you could create a Dockerfile that installs both tern and scancode using [these instructions](https://github.com/tern-tools/tern#scancode) and providing a -wd option to a directory within the Docker container. This will scan the container image for licenses (not packages yet) and give you a more detailed idea of what licenses exist per layer. Would this work for you?

**Comment by tevoinea** [comment]
> That would be great!

Awesome! I created #636 

> However, if you want to open a PR to enable this feature, we always love to have new contributors!

I'd love to 😊

The best place to start would be here? tern/analyze/docker/helpers.py, line 158

> Since Windows users are not blocked from using Tern, as vagrant is a viable and tested workaround, I would suggest using that until the overlayfs dependency is removed

>This will scan the container image for licenses (not packages yet) and give you a more detailed idea of what licenses exist per layer. Would this work for you?

For a little more context on what I'm trying to do: I'd like to have tern scanning images in build pipelines. Many of our pipelines are running Windows today and Docker is already installed. So tern running in docker on windows requires no additional dependencies and would provide a Bill of Materials for "free".

**Comment by rnjudge** [comment]
> I'd love to 😊
> 
> The best place to start would be here? tern/analyze/docker/helpers.py, line 158

Yes. I think the best place to start would be trying to solve the bug that you opened - i.e. why Tern fails when there's no valid `created_by` key. It's failing here:
```
145 def get_commands_from_history(image_layer):                                     
146     '''Given the image layer object and the shell, get the list of command      
147     objects that created the layer'''                                           
148     # set up notice origin for the layer                                        
149     origin_layer = 'Layer: ' + image_layer.fs_hash[:10]                         
150     if image_layer.created_by:                                                  
151         instruction = created_to_instruction(image_layer.created_by)            
152         image_layer.origins.add_notice_to_origins(origin_layer, Notice(         
153             formats.dockerfile_line.format(dockerfile_instruction=instruction), 
154             'info'))                                                            
155     else:                                                                       
156         image_layer.origins.add_notice_to_origins(origin_layer, Notice(         
157             formats.no_created_by, 'warning'))                                  
158     command_line = instruction.split(' ', 1)[1]   
```
In this case it's because line 158 is trying to split the `instruction` variable when the instruction variable did not get set since line 150 evaluates to false and the assignment happens only if line 150 is true. I think what we want to do is if the `created_by` variable does not exist, set it to a blank string which would subsequently return a blank `command_list`. Whether we want to do this in get_commands_from_history or in the `created_to_instruction` I need to look at a little more but feel free to experiment.

> For a little more context on what I'm trying to do: I'd like to have tern scanning images in build pipelines. Many of our pipelines are running Windows today and Docker is already installed. So tern running in docker on windows requires no additional dependencies and would provide a Bill of Materials for "free".

This is awesome to hear! We understand the need for Tern to run natively on Mac and Windows and do have this as a to-do. Do you have a familiarity with Windows Subsystem for Linux/know if it has support for overlay?
