### ISSUE TITLE
Tern fails when docker image has no created_by key

### ISSUE THREAD

**Issue by tevoinea** [tern-tools/tern#636]
**Describe the bug**
When using the experimental docker [squash](https://docs.docker.com/engine/reference/commandline/image_build/#options) feature, the resulting image has no created_by key. Running tern on this kind of image causes a crash.

**To Reproduce**
1. Start with any multi layer image
2. Enable experimental features in your docker config
3. Build your image with `--squash` argument
4. Run tern (I did it with tern in a container) on the image

**Error in terminal**
```
/* snip */
2020-04-14 20:17:02,098 - DEBUG - common - Reading files in filesystem...
Traceback (most recent call last):
  File "/usr/local/bin/tern", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/tern/__main__.py", line 201, in main
    do_main(args)
  File "/usr/local/lib/python3.8/dist-packages/tern/__main__.py", line 105, in do_main
    run.execute_docker_image(args)
  File "/usr/local/lib/python3.8/dist-packages/tern/analyze/docker/run.py", line 90, in execute_docker_image
    analyze(full_image, args)
  File "/usr/local/lib/python3.8/dist-packages/tern/analyze/docker/run.py", line 69, in analyze
    analyze_docker_image(image_obj, args.redo, dfile_lock, dfobj)
  File "/usr/local/lib/python3.8/dist-packages/tern/analyze/docker/analyze.py", line 42, in analyze_docker_image
    analyze_subsequent_layers(image_obj, shell, master_list, redo, dfobj,
  File "/usr/local/lib/python3.8/dist-packages/tern/analyze/docker/analyze.py", line 129, in analyze_subsequent_layers
    command_list = dhelper.get_commands_from_history(
  File "/usr/local/lib/python3.8/dist-packages/tern/analyze/docker/helpers.py", line 158, in get_commands_from_history
    command_line = instruction.split(' ', 1)[1]
UnboundLocalError: local variable 'instruction' referenced before assignment
```

**Expected behavior**
Tern reports on the image.

**Environment you are running Tern on**
Enter all that apply
- Output of 'tern --version' `Tern version 2.0.0 python version = 3.8.0 (default, Oct 28 2019, 16:14:01)`
- Operating System Windows
- Container OS Ubuntu 18.04
- Python version (3.6 or higher) 3.8

**Please attach files if they exist**
- tern.log
- report.*

**Comment by rnjudge** [comment]
Hi @tevoinea, are you still planning to work on this? If not I will take a look :)

**Comment by tevoinea** [comment]
Thanks for asking! You can go ahead, I don't want to block :)

**Comment by rnjudge** [comment]
@tevoinea I opened PR #681 for this fix. In order to test it, I created a squashed docker image by running `docker build --no-cache -t squashedternd . --squash`. In a container that, prior to squashing, had 3 layers, I now see only one layer of information being reported and inside the report it says the following instead of erroring out.

```
warning: No information about filesystem creation
```

If you feel so inclined, please test this change on your squashed image.

Thanks again for reporting this!

**Comment by tevoinea** [comment]
@rnjudge Thanks! The behavior sounds right to me.

Looking forward to testing it as soon as I work through some technical difficulties on my end 😊
