### ISSUE TITLE
*.tar.gz  identify error

### ISSUE THREAD

**Issue by 00032118** [tern-tools/tern#672]
**Describe the bug**
Image file recognition error, what is the reason？
**To Reproduce**

(ternenv) [root@localhost hf]# tern report -w CloudStudio-MANO-V5.20.10-image.tar.gz
2020-04-29 10:32:01,014 - DEBUG - __main__ - Starting...
2020-04-29 10:32:01,017 - DEBUG - run - Setting up...
2020-04-29 10:32:01,019 - DEBUG - rootfs - Running command: tar -tf CloudStudio-MANO-V5.20.10-image.tar.gz
2020-04-29 10:32:16,927 - DEBUG - rootfs - Running command: tar -xf CloudStudio-MANO-V5.20.10-image.tar.gz -C /root/.tern/temp
2020-04-29 10:32:33,814 - WARNING - report - Error in loading image: [Errno 2] No such file or directory: 'manifest.json'
2020-04-29 10:32:33,814 - WARNING - run - Cannot retrieve full image metadata
2020-04-29 10:32:33,814 - DEBUG - run - Teardown...
Traceback (most recent call last):
  File "/run/media/root/97c30c4f-dfbf-41ab-8f27-5230c8fed985/hf/tern-master/ternenv/bin/tern", line 11, in <module>
    sys.exit(main())
  File "/run/media/root/97c30c4f-dfbf-41ab-8f27-5230c8fed985/hf/tern-master/ternenv/lib64/python3.6/site-packages/tern/__main__.py", line 201, in main
    do_main(args)
  File "/run/media/root/97c30c4f-dfbf-41ab-8f27-5230c8fed985/hf/tern-master/ternenv/lib64/python3.6/site-packages/tern/__main__.py", line 113, in do_main
    run.execute_docker_image(args)
  File "/run/media/root/97c30c4f-dfbf-41ab-8f27-5230c8fed985/hf/tern-master/ternenv/lib64/python3.6/site-packages/tern/analyze/docker/run.py", line 99, in execute_docker_image
    report.teardown()
  File "/run/media/root/97c30c4f-dfbf-41ab-8f27-5230c8fed985/hf/tern-master/ternenv/lib64/python3.6/site-packages/tern/report/report.py", line 66, in teardown
    container.close_client()
  File "/run/media/root/97c30c4f-dfbf-41ab-8f27-5230c8fed985/hf/tern-master/ternenv/lib64/python3.6/site-packages/tern/analyze/docker/container.py", line 190, in close_client
    client.close()
AttributeError: 'NoneType' object has no attribute 'close'
(ternenv) [root@localhost hf]#

(ternenv) [root@localhost hf]# more tern.log
2020-04-29 10:32:01,014 - DEBUG - __main__ - Starting...
2020-04-29 10:32:01,017 - DEBUG - run - Setting up...
2020-04-29 10:32:01,019 - DEBUG - rootfs - Running command: tar -tf CloudStudio-MANO-V5.20.10-image.tar.gz
2020-04-29 10:32:16,927 - DEBUG - rootfs - Running command: tar -xf CloudStudio-MANO-V5.20.10-image.tar.gz -C
root/.tern/temp
2020-04-29 10:32:33,814 - WARNING - report - Error in loading image: [Errno 2] No such file or directory: 'man
fest.json'
2020-04-29 10:32:33,814 - WARNING - run - Cannot retrieve full image metadata
2020-04-29 10:32:33,814 - DEBUG - run - Teardown...

(ternenv) [root@localhost hf]# uname -a
Linux localhost.localdomain 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by nishakm** [comment]
How was `CloudStudio-MANO-V5.20.10-image.tar.gz` created? Is it a docker image? What version of docker?

**Comment by 00032118** [comment]
sorry,Thanks for your answers, I made a mistake
