### ISSUE TITLE
tern 2.1.0 -w *.tar error

### ISSUE THREAD

**Issue by 00032118** [tern-tools/tern#719]
(tven) [root@localhost hf]# tern --version
Tern version 2.1.0
   python version = 3.6.8 (default, Apr  2 2020, 13:34:55)
(tven) [root@localhost hf]#tern report -w vru-cudr-sys-mp.tar -x cve_bin_tool
2020-06-04 11:55:06,567 - DEBUG - __main__ - Starting...
2020-06-04 11:55:06,570 - DEBUG - run - Setting up...
2020-06-04 11:55:06,572 - DEBUG - container - Checking if image "vru-cudr-sys-mp.tar" is available on disk...
Traceback (most recent call last):
  File "/home/hf/tven/bin/tern", line 8, in <module>
    sys.exit(main())
  File "/home/hf/tven/lib64/python3.6/site-packages/tern/__main__.py", line 201, in main
    do_main(args)
  File "/home/hf/tven/lib64/python3.6/site-packages/tern/__main__.py", line 113, in do_main
    run.execute_docker_image(args)
  File "/home/hf/tven/lib64/python3.6/site-packages/tern/analyze/docker/run.py", line 83, in execute_docker_image
    full_image = report.load_full_image(image_string)
  File "/home/hf/tven/lib64/python3.6/site-packages/tern/report/report.py", line 113, in load_full_image
    test_image = DockerImage(image_tag_string)
  File "/home/hf/tven/lib64/python3.6/site-packages/tern/classes/docker_image.py", line 42, in __init__
    docker_image = container.check_image(self.__repotag)
  File "/home/hf/tven/lib64/python3.6/site-packages/tern/analyze/docker/container.py", line 80, in check_image
    image = client.images.get(image_tag_string)
AttributeError: 'NoneType' object has no attribute 'images'

**Comment by 00032118** [comment]
-i param is ok !!!!!(tven) [root@localhost hf]# tern report -i vru-cudr-sys-mp:V7.20.14.I3 -x cve_bin_tool
2020-06-04 11:59:46,241 - DEBUG - __main__ - Starting...
2020-06-04 11:59:46,242 - DEBUG - run - Setting up...
2020-06-04 11:59:46,251 - DEBUG - container - Checking if image "vru-cudr-sys-mp:V7.20.14.I3" is available on disk...
2020-06-04 11:59:46,258 - DEBUG - container - Image "vru-cudr-sys-mp:V7.20.14.I3" found
2020-06-04 11:59:46,259 - DEBUG - container - Checking if image "vru-cudr-sys-mp:V7.20.14.I3" is available on disk...
2020-06-04 11:59:46,265 - DEBUG - container - Image "vru-cudr-sys-mp:V7.20.14.I3" found
2020-06-04 11:59:52,332 - DEBUG - rootfs - Running command: tar -tf /root/.tern/temp.tar
2020-06-04 11:59:52,339 - DEBUG - rootfs - Running command: tar -x --exclude=.wh.* -f /root/.tern/temp.tar -C /root/.tern/temp
2020-06-04 11:59:52,849 - DEBUG - rootfs - Running command: tar -tf /root/.tern/temp/37acfbe6ca863d25dcd3596a657e4073183e5a2f398ae6c508b6f8a9ca352de2/layer.tar
2020-06-04 11:59:52,884 - DEBUG - rootfs - Running command: tar -x --exclude=.wh.* -f /root/.tern/temp/37acfbe6ca863d25dcd3596a657e4073183e5a2f398ae6c508b6f8a9ca352de2/layer.tar -C /root/.tern/temp/37acfbe6ca863d25dcd3596a657e4073183e5a2f398ae6c508b6f8a9ca352de2/contents
2020-06-04 11:59:53,275 - DEBUG - rootfs - Running command: /home/hf/tven/lib64/python3.6/site-packages/tern/tools/fs_hash.sh /root/.tern/temp/37acfbe6ca863d25dcd3596a657e4073183e5a2f398ae6c508b6f8a9ca352de2/contents

**Comment by rnjudge** [comment]
@00032118 can you provide the tarball so we can debug? Or is `vru-cudr-sys-mp:V7.20.14.I3` an image that we can pull into a tarball from dockerhub?

**Comment by rnjudge** [comment]
This is a newer issue. When I run with Tern at commit 93da3799c3004d2147ce17f40ce556b35c552579, I am not able to reproduce this issue with raw image tarball.

**Comment by rnjudge** [comment]
> @00032118 can you provide the tarball so we can debug? Or is `vru-cudr-sys-mp:V7.20.14.I3` an image that we can pull into a tarball from dockerhub?

Nevermind, I can reproduce this with any image tarball and Tern v2.1.0.

**Comment by rnjudge** [comment]
This line is very suspicious to me, it shouldn't be checking if Tern is available on disk as the raw image is already present, it should go straight to the untarring.

```
2020-06-04 11:55:06,572 - DEBUG - container - Checking if image "vru-cudr-sys-mp.tar" is available on disk...
```

FWIW, I am working on an old branch at commit 54b5cb7 and cannot reproduce this issue.

**Comment by 00032118** [comment]
I have replied to your email, version 2.0 does not have this problem.

**Comment by 00032118** [comment]
(Pdb) l
 77         logger.debug(
 78             "Checking if image \"%s\" is available on disk...", image_tag_string)
 79         try:
 80             import pdb
 81             pdb.set_trace()
 82  ->         image = client.images.get(image_tag_string)
 83             logger.debug("Image \"%s\" found", image_tag_string)
 84             return image
 85         except docker.errors.ImageNotFound:
 86             return None
 87
(Pdb) s
> /home/hf/tven/lib64/python3.6/site-packages/tern/analyze/docker/container.py(85)check_image()
-> except docker.errors.ImageNotFound:
(Pdb) p image_tag_string
'./test/hf.tar'
(Pdb) p client
None
