### ISSUE TITLE
Regression tern 2.2.0: ValueError: No escaped character

### ISSUE THREAD

**Issue by makefu** [tern-tools/tern#819]
**Describe the bug**
When trying to analyze the logstash container tern errors with "ValueError: No escaped character"

**To Reproduce**
`tern report -f json -i docker.elastic.co/logstash/logstash-oss:7.5.1`
**Error in terminal**
```
2020-11-03 21:15:11,628 - DEBUG - common - Reading files in filesystem...
1
Traceback (most recent call last):
  File "/nix/store/3rafgmsf379gc35hqjq70nj03fdqk4wv-python3.7-tern-2.2.0/bin/.tern-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/ylfgyb6175xk068axhjbdq9sykj14nx6-python3-3.7.8-env/lib/python3.7/site-packages/tern/__main__.py", line 204, in main
    do_main(args)
  File "/nix/store/ylfgyb6175xk068axhjbdq9sykj14nx6-python3-3.7.8-env/lib/python3.7/site-packages/tern/__main__.py", line 105, in do_main
    run.execute_docker_image(args)
  File "/nix/store/ylfgyb6175xk068axhjbdq9sykj14nx6-python3-3.7.8-env/lib/python3.7/site-packages/tern/analyze/docker/run.py", line 91, in execute_docker_image
    analyze(full_image, args)
  File "/nix/store/ylfgyb6175xk068axhjbdq9sykj14nx6-python3-3.7.8-env/lib/python3.7/site-packages/tern/analyze/docker/run.py", line 70, in analyze
    args.driver)
  File "/nix/store/ylfgyb6175xk068axhjbdq9sykj14nx6-python3-3.7.8-env/lib/python3.7/site-packages/tern/analyze/docker/analyze.py", line 43, in analyze_docker_image
    dfile_lock, driver)
  File "/nix/store/ylfgyb6175xk068axhjbdq9sykj14nx6-python3-3.7.8-env/lib/python3.7/site-packages/tern/analyze/docker/analyze.py", line 140, in analyze_subsequent_layers
    image_obj.layers[curr_layer])
  File "/nix/store/ylfgyb6175xk068axhjbdq9sykj14nx6-python3-3.7.8-env/lib/python3.7/site-packages/tern/analyze/docker/helpers.py", line 176, in get_commands_from_history
    command_list, msg = common.filter_install_commands(command_line)
  File "/nix/store/ylfgyb6175xk068axhjbdq9sykj14nx6-python3-3.7.8-env/lib/python3.7/site-packages/tern/analyze/common.py", line 511, in filter_install_commands
    command_list, branch_report = get_shell_commands(shell_command_line)
  File "/nix/store/ylfgyb6175xk068axhjbdq9sykj14nx6-python3-3.7.8-env/lib/python3.7/site-packages/tern/analyze/common.py", line 36, in get_shell_commands
    statements = general.split_command(shell_command_line)
  File "/nix/store/ylfgyb6175xk068axhjbdq9sykj14nx6-python3-3.7.8-env/lib/python3.7/site-packages/tern/utils/general.py", line 98, in split_command
    statements.append(parse_shell_variables_and_command(cmd))
  File "/nix/store/ylfgyb6175xk068axhjbdq9sykj14nx6-python3-3.7.8-env/lib/python3.7/site-packages/tern/utils/general.py", line 133, in parse_shell_variables_and_command
    statement['command'] = clean_command(concatenated_command)
  File "/nix/store/ylfgyb6175xk068axhjbdq9sykj14nx6-python3-3.7.8-env/lib/python3.7/site-packages/tern/utils/general.py", line 51, in clean_command
    return ' '.join(shlex.split(command))
  File "/nix/store/wpw6qdjbrv7s72kk81n1lwf3vj6fldk2-python3-3.7.8/lib/python3.7/shlex.py", line 310, in split
    return list(lex)
  File "/nix/store/wpw6qdjbrv7s72kk81n1lwf3vj6fldk2-python3-3.7.8/lib/python3.7/shlex.py", line 299, in __next__
    token = self.get_token()
  File "/nix/store/wpw6qdjbrv7s72kk81n1lwf3vj6fldk2-python3-3.7.8/lib/python3.7/shlex.py", line 109, in get_token
    raw = self.read_token()
  File "/nix/store/wpw6qdjbrv7s72kk81n1lwf3vj6fldk2-python3-3.7.8/lib/python3.7/shlex.py", line 210, in read_token
    raise ValueError("No escaped character")
ValueError: No escaped character
```

**Expected behavior**
tern writes json report to stdout

**Environment you are running Tern on**
Enter all that apply
- Output of 'tern --version':
```
  Tern at commit e24207a83710178f86505ba42484dc53c3436d6c
python version = 3.7.8 (default, Jun 27 2020, 09:38:56)
```
- Operating System (Linux Distro and version or Mac or Windows):
NixOS Linux Distribution

**Please attach files if they exist**

[tern.log](https://github.com/tern-tools/tern/files/5483851/tern.log)

**Comment by nishakm** [comment]
@makefu Would you be able to provide the Dockerfile that created `docker.elastic.co/logstash/logstash-oss:7.5.1`?

**Comment by makefu** [comment]
according to the documentation, https://github.com/elastic/dockerfiles/blob/v7.5.1/logstash/Dockerfile is being used to build the official docker image

**Comment by nishakm** [comment]
@makefu I am unable to recreate the error at the tip of master. Could you try again?

**Comment by makefu** [comment]
sorry for the late response, i will be able to check tomorrow if the error is still there :)
cheers
