### ISSUE TITLE
Can't generate html output when running with scancode

### ISSUE THREAD

**Issue by aalexanderr** [tern-tools/tern#844]
**Describe the bug**
Can't generate html output when running tern with scancode:

**To Reproduce**
1. git clone "https://gerrit.onap.org/r/integration/docker/onap-python"
1. cd onap-python
1. either:
    1. docker build -t onappython - < Dockerfile && tern report -x scancode -f html -o report.html  -i onappython:latest
    1. tern report -x scancode -f html -o report.html  -d Dockerfile
1. See error

**Error in terminal**
```
2020-12-15 22:22:03,866 - DEBUG - executor - Collecting file data...
2020-12-15 22:22:04,104 - DEBUG - generator - Creating HTML report...
Traceback (most recent call last):
  File "/home/vagrant/ternenv/bin/tern", line 8, in <module>
    sys.exit(main())
  File "/home/vagrant/ternenv/lib/python3.6/site-packages/tern/__main__.py", line 192, in main
    do_main(args)
  File "/home/vagrant/ternenv/lib/python3.6/site-packages/tern/__main__.py", line 95, in do_main
    crun.execute_image(args)
  File "/home/vagrant/ternenv/lib/python3.6/site-packages/tern/analyze/default/container/run.py", line 87, in execute_image
    report.report_out(args, full_image)
  File "/home/vagrant/ternenv/lib/python3.6/site-packages/tern/report/report.py", line 70, in report_out
    report = generate_report(args, *images)
  File "/home/vagrant/ternenv/lib/python3.6/site-packages/tern/report/report.py", line 50, in generate_report
    return generate_format(images, args.report_format)
  File "/home/vagrant/ternenv/lib/python3.6/site-packages/tern/report/report.py", line 64, in generate_format
    return mgr.driver.generate(images)
  File "/home/vagrant/ternenv/lib/python3.6/site-packages/tern/formats/html/generator.py", line 299, in generate
    report = create_html_report(report_dict, image_obj_list)
  File "/home/vagrant/ternenv/lib/python3.6/site-packages/tern/formats/html/generator.py", line 278, in create_html_report
    report = report + '\n' + write_licenses(image_obj_list)
  File "/home/vagrant/ternenv/lib/python3.6/site-packages/tern/formats/html/generator.py", line 256, in write_licenses
    licenses = get_licenses_only(image_obj_list)
  File "/home/vagrant/ternenv/lib/python3.6/site-packages/tern/report/content.py", line 40, in get_licenses_only
    pkg_licenses = get_layer_packages_licenses(layer)
  File "/home/vagrant/ternenv/lib/python3.6/site-packages/tern/report/content.py", line 19, in get_layer_packages_licenses
    package_licenses = get_package_licenses(package)
  File "/home/vagrant/ternenv/lib/python3.6/site-packages/tern/report/content.py", line 54, in get_package_licenses
    pkg_licenses.add(package.pkg_license)
TypeError: unhashable type: 'dict'

```

**Expected behavior**
Get a html report

**Environment you are running Tern on**
Enter all that apply
- Output of 'tern --version'
Tern version 2.3.0
   python version = 3.6.12 (default, Aug 17 2020, 23:45:20) 
- Operating System (Linux Distro and version or Mac or Windows)
  Ubuntu 20.04
- Vagrant file
[Vagrantfile.txt](https://github.com/tern-tools/tern/files/5699351/Vagrantfile.txt)
(had to add extension otherwise github complained it is not supported)
- Container OS
N/A
- Python version (3.6 or higher)
Python 3.6.12
- Cloud environment (AWS, Azure, GCP)
N/A

**Please attach files if they exist**
- tern.log
[tern.log](https://github.com/tern-tools/tern/files/5699347/tern.log)
- report.*
N/A

**Comment by rnjudge** [comment]
@abhaykatheria do you want to take a look at this?

**Comment by abhaykatheria** [comment]
Oh ok cool.

**Comment by abhaykatheria** [comment]
@aalexanderr @rnjudge  I ran tern on the given image using same commands(BOTH OF THEM) and it ran well. 
Here's the report I got.
[report.html](https://drive.google.com/file/d/1CI76HzJdlR1RP-RfVzvX74A8zjyybeus/view?usp=sharing)

And these are the logs

`tern report -x scancode -f html -o report.html -d Dockerfile`
log-1
[tern.log](https://github.com/tern-tools/tern/files/5715209/tern.log)


`docker build -t onappython - < Dockerfile && tern report -x scancode -f html -o report.html -i onappython:latest`
log-2
[tern.log](https://github.com/tern-tools/tern/files/5715214/tern.log)

@aalexanderr  I would recommend updating tern and scancode-toolkit.

**Comment by aalexanderr** [comment]
@abhaykatheria 
What version of tern did you use? The html report links to this commit:
https://github.com/tern-tools/tern/commit/c8f336a7137e0f34d7cb7a55ee4fcb9cf104b7b4
but it shows me 404.

I've checked your fork but the only active branch I see (master) is the same as here.

Both tern and scancode I used  are latest releases
```
$ scancode --version
ScanCode version 3.2.3
Tern version:
$ tern --version
Tern version 2.3.0
python version = 3.6.12 (default, Aug 17 2020, 23:45:20)
```

(before submitting I have verifed it on 2 different host machines with different vagrant versions and two different versions of generic/ubuntu2004 versions (latest and a bit older one).

**Comment by abhaykatheria** [comment]
I installed it manually from the source code (Instructions are in [contribution.md](https://github.com/tern-tools/tern/blob/master/CONTRIBUTING.md#setting-up-a-development-environment-on-mac-and-windows)). I didn't made any commits I checked the git logs. its strange the commit checksum in report is pointing to nowhere. @rnjudge can you take a look at this ..?

**Comment by aalexanderr** [comment]
I did everything as in linked contributing, then `pip3 install scancode-toolkit[full]` and went with  steps to reproduce.
It resulted in the same error as initially reported.
BTW the unknown hash is the last commit from the onap-python repo :)

**Comment by rnjudge** [comment]
Bumping the priority on this. Will work on a fix in the next week or two.

**Comment by rnjudge** [comment]
@aalexanderr Sincere apologies for the delay on this fix. Should work now.
