### ISSUE TITLE
Analysis of images from nexus repositories stopped working

### ISSUE THREAD

**Issue by aalexanderr** [tern-tools/tern#890]
**Describe the bug**

**To Reproduce**
1. Install tern (tried both from main and master)
2. run tern report -i nexus3.onap.org:10001/onap/so/so-oof-adapter:1.7.11

**Error in terminal**
```
$ tern report -i nexus3.onap.org:10001/onap/so/so-oof-adapter:1.7.11
2021-02-24 13:32:01,465 - DEBUG - __main__ - Starting...
2021-02-24 13:32:01,465 - DEBUG - prep - Setting up...
2021-02-24 13:32:01,465 - DEBUG - run - Starting analysis...
2021-02-24 13:32:01,543 - DEBUG - docker_api - Checking if image "nexus3.onap.org:10001/onap/so/so-oof-adapter:1.7.11" is available on disk...
2021-02-24 13:32:01,549 - DEBUG - docker_api - Image "nexus3.onap.org:10001/onap/so/so-oof-adapter:1.7.11" found
2021-02-24 13:32:05,481 - DEBUG - rootfs - Running command: tar -tf /home/amazuruk/.tern/temp.tar
2021-02-24 13:32:05,487 - DEBUG - rootfs - Running command: tar -x --exclude=.wh.* -f /home/amazuruk/.tern/temp.tar -C /home/amazuruk/.tern/temp
Traceback (most recent call last):
  File "/home/amazuruk/ternenv/bin/tern", line 10, in <module>
    sys.exit(main())
  File "/home/amazuruk/ternenv/lib/python3.6/site-packages/tern/__main__.py", line 254, in main
    do_main(args)
  File "/home/amazuruk/ternenv/lib/python3.6/site-packages/tern/__main__.py", line 101, in do_main
    crun.execute_image(args)
  File "/home/amazuruk/ternenv/lib/python3.6/site-packages/tern/analyze/default/container/run.py", line 78, in execute_image
    full_image = cimage.load_full_image(image_string, args.load_until_layer)
  File "/home/amazuruk/ternenv/lib/python3.6/site-packages/tern/analyze/default/container/image.py", line 29, in load_full_image
    test_image = DockerImage(image_tag_string)
  File "/home/amazuruk/ternenv/lib/python3.6/site-packages/tern/classes/docker_image.py", line 36, in __init__
    self._name = repo_dict.get('name')
AttributeError: 'NoneType' object has no attribute 'get'

```

**Expected behavior**
Analysis proceeds

**Environment you are running Tern on**
Enter all that apply
- Output of 'tern --version'
- Operating System (Linux Distro and version or Mac or Windows)
- Vagrant file
- Container OS
- Python version (3.6 or higher)
- Cloud environment (AWS, Azure, GCP)

ubuntu on host:
```
$ tern --version
Tern at commit 11fc8a33eb52eb8ebdb17e14b80bf3605160bd7a
   python version = 3.6.9 (default, Oct  8 2020, 12:12:24) 
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
```
debian10 in k8 pod (unknown hypervisor)
```
$ tern --version
Tern version 2.4.0
   python version = 3.7.3 (default, Jul 25 2020, 13:03:44)
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

**Please attach files if they exist**
- tern.log
- report.*
tern didnt get to create either, log printed to stderr is pasted earlier in the ticket

**Comment by rnjudge** [comment]
`tern-2.3.0` successfully creates a report for `nexus3.onap.org:10001/onap/so/so-oof-adapter:1.7.11` so this is a regression somewhere in the changelog listed here: https://github.com/tern-tools/tern/blob/v2.4.0/docs/releases/v2_4_0.md

**Comment by nishakm** [comment]
The parsing is definitely broken. #891 may be the fix for it. But the DockerImage instance is working i.e. no stacktrace at that point. So the problem is somewhere else.

**Comment by nishakm** [comment]
Aha! The final string that gets passed is `nexus3.onap.org:10001/onap/so/so-oof-adapter@sha256:d7e1f739ba732c853a638f9c90becd5e0f8d313c8d506567b0b83ac38a1d53cb` so that definitely confuses the parser.

**Comment by rnjudge** [comment]
Good catch @aalexanderr. I think this is a side effect of e1d00f8.
