### ISSUE TITLE
Problem while running tern on linux

### ISSUE THREAD

**Issue by JustinWonjaePark** [tern-tools/tern#971]
I was running tern 2.5 on Ubuntu 16.04 (with venv and pip install) and it worked just fine as expected.

I was working on other tools and I think I messed up the system a little bit.
Whenever I run tern ('tern report' or simply 'tern') I get error message related to JSONDecodeError.

`(ternenv) mymachine[user /home/user/ternenv]$ tern
2021-05-21 14:10:24,431 - DEBUG - __main__ - Starting...
2021-05-21 14:10:24,432 - DEBUG - prep - Setting up...
Traceback (most recent call last):
  File "/home/user/ternenv/bin/tern", line 11, in <module>
    sys.exit(main())
  File "/home/user/ternenv/lib/python3.6/site-packages/tern/__main__.py", line 259, in main
    do_main(args)
  File "/home/user/ternenv/lib/python3.6/site-packages/tern/__main__.py", line 91, in do_main
    prep.setup(args.working_dir)
  File "/home/user/ternenv/lib/python3.6/site-packages/tern/prep.py", line 34, in setup
    cache.load()
  File "/home/user/ternenv/lib/python3.6/site-packages/tern/utils/cache.py", line 42, in load
    cache = json.load(f)
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 7080343 (char 7080342)`

I've tried creating ternenv and installing python again but didn't worked.
Is there anybody who had similar experiance?

**Comment by rnjudge** [comment]
@JustinWonjaePark I have seen this error before and indeed it is an issue with the cache file not with Tern itself. What happens if you remove the cache file located at `~/.tern/cache.json`, does that help?

**Comment by JustinWonjaePark** [comment]
@rnjudge That did help!!
Thanks a lot!
