### ISSUE TITLE
Scancode is no longer in path on Dockerfile.scancode

### ISSUE THREAD

**Issue by maxhbr** [tern-tools/tern#979]
**Describe the bug**
After change  #977 that fixed https://github.com/tern-tools/tern/issues/976, scancode is no longer in PATH on the docker image.

**To Reproduce**
1. Buiild latest `Dockerfile.scancode`
  - see ` RUN pip install -r /install/requirements.scancode.txt`, that shows that the new code is used
2. try to run scancode, see that it is not in PATH

```
Klone nach '/tmp/tmp.EbpG59CCKz' ...
remote: Enumerating objects: 6329, done.
remote: Counting objects: 100% (249/249), done.
remote: Compressing objects: 100% (165/165), done.
remote: Total 6329 (delta 143), reused 137 (delta 83), pack-reused 6080
Empfange Objekte: 100% (6329/6329), 6.45 MiB | 3.47 MiB/s, fertig.
Löse Unterschiede auf: 100% (4033/4033), fertig.
[+] Building 1.3s (14/14) FINISHED
 => [internal] load build definition from Dockerfile.scancode                                                                                                                                                  0.1s
 => => transferring dockerfile: 1.16kB                                                                                                                                                                         0.0s
 => [internal] load .dockerignore                                                                                                                                                                              0.1s
 => => transferring context: 2B                                                                                                                                                                                0.0s
 => [internal] load metadata for docker.io/library/python:3.9-slim-buster                                                                                                                                      1.1s
 => [base 1/1] FROM docker.io/library/python:3.9-slim-buster@sha256:80b238ba357d98813bcc425f505dfa238f49cf5f895492fc2667af118dccaa44                                                                           0.0s
 => [internal] load build context                                                                                                                                                                              0.0s
 => => transferring context: 1.48kB                                                                                                                                                                            0.0s
 => CACHED [stage-2 1/2] RUN echo "deb http://deb.debian.org/debian bullseye main" > /etc/apt/sources.list.d/bullseye.list     && echo "Package: *\nPin: release n=bullseye\nPin-Priority: 50" > /etc/apt/pre  0.0s
 => CACHED [builder 1/6] RUN mkdir /install                                                                                                                                                                    0.0s
 => CACHED [builder 2/6] WORKDIR /install                                                                                                                                                                      0.0s
 => CACHED [builder 3/6] RUN apt-get update     && apt-get install -y --no-install-recommends     build-essential     && rm -rf /var/lib/apt/lists/*                                                           0.0s
 => CACHED [builder 4/6] RUN pip install --no-warn-script-location --prefix=/install     tern                                                                                                                  0.0s
 => CACHED [builder 5/6] COPY docker/requirements.scancode.txt /install/requirements.scancode.txt                                                                                                              0.0s
 => CACHED [builder 6/6] RUN pip install -r /install/requirements.scancode.txt                                                                                                                                 0.0s
 => CACHED [stage-2 2/2] COPY --from=builder /install /usr/local                                                                                                                                               0.0s
 => exporting to image                                                                                                                                                                                         0.0s
 => => exporting layers                                                                                                                                                                                        0.0s
 => => writing image sha256:20f9c185ad97d1b5a897b0ac4aa9a3f54b0a7bd9c984816b20bb220f65fa83c1                                                                                                                   0.0s
 => => naming to docker.io/library/mytern:latest                                                                                                                                                               0.0s
++ pwd
+ docker run -it --privileged --device /dev/fuse -v /var/run/docker.sock:/var/run/docker.sock -v :/workdir -v /tmp/tmp.go3sGhrf2F:/out -w /out --entrypoint /bin/bash --rm mytern:latest
root@a829af94b4dc:/out# scancode
bash: scancode: command not found
```

**Error in terminal**

A tern run ends with:
```
[...]
2021-05-28 15:18:15,411 - DEBUG - rootfs - Running command: chmod +x /usr/local/lib/python3.9/site-packages/tern/tools/fs_hash.sh
2021-05-28 15:18:15,414 - DEBUG - rootfs - Running command: /usr/local/lib/python3.9/site-packages/tern/tools/fs_hash.sh /root/.tern/temp/ad4902bb04f54ddd280af81bffb97be49e9832487b913d399facf6b72d7bb480/contents
2021-05-28 15:18:15,427 - DEBUG - common - Reading files in filesystem...
Traceback (most recent call last):
  File "/usr/local/bin/tern", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/tern/__main__.py", line 275, in main
    do_main(args)
  File "/usr/local/lib/python3.9/site-packages/tern/__main__.py", line 116, in do_main
    crun.execute_image(args)
  File "/usr/local/lib/python3.9/site-packages/tern/analyze/default/container/run.py", line 88, in execute_image
    cimage.analyze(full_image, args)
  File "/usr/local/lib/python3.9/site-packages/tern/analyze/default/container/image.py", line 73, in analyze
    passthrough.run_extension(image_obj, options.extend, options.redo)
  File "/usr/local/lib/python3.9/site-packages/tern/analyze/passthrough.py", line 127, in run_extension
    return mgr.driver.execute(image_obj, redo)
  File "/usr/local/lib/python3.9/site-packages/tern/extensions/scancode/executor.py", line 191, in execute
    file_list, package_list = collect_layer_data(layer)
  File "/usr/local/lib/python3.9/site-packages/tern/extensions/scancode/executor.py", line 133, in collect_layer_data
    full_cmd = get_filesystem_command(layer_obj, command)
  File "/usr/local/lib/python3.9/site-packages/tern/analyze/passthrough.py", line 48, in get_filesystem_command
    cmd_list = get_exec_command(command)
  File "/usr/local/lib/python3.9/site-packages/tern/analyze/passthrough.py", line 35, in get_exec_command
    raise OSError("Command {} not found".format(run_bin))
OSError: Command scancode not found

```

**Environment you are running Tern on**
same as #976 , but with #977 in the sources

**Comment by JeroenKnoops** [comment]
I'm testing the implementation right now

**Comment by maxhbr** [comment]
The fix works for me
