### ISSUE TITLE
Running tern with Scancode results error

### ISSUE THREAD

**Issue by JustinWonjaePark** [tern-tools/tern#982]
I installed Tern 2.6.1, Scancode 21.3.31 on Ubuntu 16.04.

I ran Tern report with Scancode extension with command 
`tern report -f html -x scancode -i fossology/fossology:3.10.0 -o tern_fossology_scancode.html` 
and got error message
`...
2021-06-04 10:48:37,149 - DEBUG - executor - Collecting file data...
2021-06-04 10:48:42,563 - DEBUG - generator - Creating HTML report...
Traceback (most recent call last):
  File "/home/user/scanenv-with-scancode/bin/tern", line 11, in <module>
    sys.exit(main())
  File "/home/user/scanenv-with-scancode/lib/python3.6/site-packages/tern/__main__.py", line 275, in main
    do_main(args)
  File "/home/user/scanenv-with-scancode/lib/python3.6/site-packages/tern/__main__.py", line 116, in do_main
    crun.execute_image(args)
  File "/home/user/scanenv-with-scancode/lib/python3.6/site-packages/tern/analyze/default/container/run.py", line 90, in execute_image
    report.report_out(args, full_image)
  File "/home/user/scanenv-with-scancode/lib/python3.6/site-packages/tern/report/report.py", line 95, in report_out
    report = generate_report(args, *images)
  File "/home/user/scanenv-with-scancode/lib/python3.6/site-packages/tern/report/report.py", line 51, in generate_report
    images, args.report_format, args.print_inclusive)
  File "/home/user/scanenv-with-scancode/lib/python3.6/site-packages/tern/report/report.py", line 65, in generate_format
    return mgr.driver.generate(images, print_inclusive)
  File "/home/user/scanenv-with-scancode/lib/python3.6/site-packages/tern/formats/html/generator.py", line 321, in generate
    report = create_html_report(report_dict, image_obj_list)
  File "/home/user/scanenv-with-scancode/lib/python3.6/site-packages/tern/formats/html/generator.py", line 300, in create_html_report
    report = report + '\n' + write_licenses(image_obj_list)
  File "/home/user/scanenv-with-scancode/lib/python3.6/site-packages/tern/formats/html/generator.py", line 278, in write_licenses
    licenses = get_licenses_only(image_obj_list)
  File "/home/user/scanenv-with-scancode/lib/python3.6/site-packages/tern/report/content.py", line 40, in get_licenses_only
    pkg_licenses = get_layer_packages_licenses(layer)
  File "/home/user/scanenv-with-scancode/lib/python3.6/site-packages/tern/report/content.py", line 19, in get_layer_packages_licenses
    package_licenses = get_package_licenses(package)
  File "/home/user/scanenv-with-scancode/lib/python3.6/site-packages/tern/report/content.py", line 54, in get_package_licenses
    pkg_licenses.add(package.pkg_license)
TypeError: unhashable type: 'list'`

Running it with Dockerfile with following command resulted similarly.
` tern report -x scancode -f html -d ~/scan_tern/fossology/fossology_src/Dockerfile -o tern_fossology_scancode.html`

Is there any suggestion to get the work done?

PS : running Tern report without Scancode extension and Scancode scan itself were successful.

**Comment by rnjudge** [comment]
Thanks for the bug @JustinWonjaePark. This is actually an error with the `html` format generation not scancode (as you mentioned) and the issue was raised previously in https://github.com/tern-tools/tern/issues/844. I'll bump the priority on this issue. Keep an eye on #844 for a fix.

**Comment by JustinWonjaePark** [comment]
Thanks for fast reply!! :)

**Comment by rnjudge** [comment]
@JustinWonjaePark Apologies for the delay in getting this fixed. Should work now!
